#!/bin/bash
#SBATCH --job-name=LS
#SBATCH --output=out.out
#SBATCH --chdir /home/gravina/DL-Fleuret
#SBATCH --mail-type all
#SBATCH --mail-user luca.gravina@epfl.ch
#SBATCH --time 5:00:00
#SBATCH --nodes 1
#SBATCH --ntasks 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 28
#SBATCH --mem-per-cpu 4G
#SBATCH --account=ltpn
#SBATCH --array=0-5

N=${SLURM_ARRAY_TASK_ID}

echo BEGIN at `date`
python3 RUN_oute.py --Njob $N
echo FINISHED at `date`